core-identity-uri: ${SERVICE_SCHEME}://${CORE_IDENTITY_HOST}:${CORE_IDENTITY_PORT}
core-gateway-uri: ${SERVICE_SCHEME}://${CORE_GATEWAY_HOST}:${CORE_GATEWAY_PORT}

app:
  domain-name: ${APP_DOMAIN}
  base-uri: ${SLATE_URI}
  dev-uris: ${DEV_SLATE_URI}

server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: core-gateway
  cloud:
    gateway:
      mvc:
        routes:
          # Identity Api Route Configuration
          - id: identity_route
            uri: ${core-identity-uri}
            predicates:
              - Path=/api/identity/**
            filters:
              - TokenRelay=
              - StripPrefix=2

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  
  security:
    oauth2:
      client:
        provider:
          core-identity:
            issuer-uri: "${AUTH_SERVER}"
        registration:
          ginkgoo-web-client:
            provider: core-identity
            client-id: ginkgoo-web-client
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "${AUTH_CLIENT}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email

management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}
    com.ginkgooai: ${LOG_LEVEL_GINKGOOAI:DEBUG}

