authorization-server-uri: ${scheme}://${core_identity_host}:${core_identity_port}
slate-uri: ${scheme}://${slate_host}:${slate_port}
authorities-json-path:
audience:

app:
  base-uri: ${scheme}://${slate_host}:${slate_port}

server:
  port: ${core_gateway_port}
  forward-headers-strategy: native

spring:
  application:
    name: core-gateway
  cloud:
    gateway:
      mvc:
        routes:
          # Identity Api Route Configuration
          - id: identity_route
            uri: http://${core_identity_host}:${core_identity_port}
            predicates:
              - Path=/api/identity/**
            filters:
              - TokenRelay=
              - StripPrefix=2

  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
  
  security:
    oauth2:
      client:
        provider:
          core-identity:
            issuer-uri: http://${core_identity_host}:${core_identity_port}
        registration:
          ginkgoo-web-client:
            provider: core-identity
            client-id: ginkgoo-web-client
            client-secret: ${client_secret}
            authorization-grant-type: authorization_code
            redirect-uri: "http://${slate_host}:${core_gateway_port}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ginkgooai.core.gateway: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    org.springframework.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE
