core-identity-uri: ${SERVICE_SCHEME}://${CORE_IDENTITY_HOST}:${CORE_IDENTITY_PORT}
core-gateway-uri: ${SERVICE_SCHEME}://${CORE_GATEWAY_HOST}:${CORE_GATEWAY_PORT}
core-workspace-uri: ${SERVICE_SCHEME}://${CORE_WORKSPACE_HOST}:${CORE_WORKSPACE_PORT}
core-project-uri: ${SERVICE_SCHEME}://${CORE_PROJECT_HOST}:${CORE_PROJECT_PORT}
core-storage-uri: ${SERVICE_SCHEME}://${CORE_STORAGE_HOST}:${CORE_STORAGE_PORT}
core-ai-uri: ${SERVICE_SCHEME}://${CORE_AI_HOST}:${CORE_AI_PORT}
core-messaging-uri: ${SERVICE_SCHEME}://${CORE_MESSAGING_HOST}:${CORE_MESSAGING_PORT}
legal-case-uri: ${SERVICE_SCHEME}://${LEGAL_CASE_HOST}:${LEGAL_CASE_PORT}

auth-server-uri: ${AUTH_SERVER}

app:
  domain-name: ${APP_DOMAIN}
  base-uri: ${APP_URI}
  api-uri: ${AUTH_CLIENT}
  dev-uris: ${DEV_APP_URI}
  rate-limit:
    capacity: 100
    period-minutes: 1

server:
  port: ${CORE_GATEWAY_PORT}
  forward-headers-strategy: native
  servlet:
    session:
      timeout: 1D
      cookie:
        name: AUTH_SESSION

spring:
  application:
    name: core-gateway
  codec:
    max-in-memory-size: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  cloud:
    gateway:
      mvc:
        routes:
          # Identity OpenApi Route Configuration
          - id: identity_openapi_route
            uri: ${core-identity-uri}
            predicates:
              - Path=/api/identity/v3/**, /api/identity/swagger-ui/**
            filters:
           
          # Identity Api Route Configuration
          - id: identity_route
            uri: ${core-identity-uri}
            predicates:
              - Path=/api/identity/**
            filters:
              - TokenRelay=
              - StripPrefix=2
          
          # Workspace OpenApi Route Configuration
          - id: workspace_openapi_route
            uri: ${core-workspace-uri}
            predicates:
              - Path=/api/workspace/v3/**,/api/workspace/swagger-ui/**
            filters:

          # Workspace Api Route Configuration
          - id: workspace_route
            uri: ${core-workspace-uri}
            predicates:
              - Path=/api/workspace/**
            filters:
              - TokenRelay=
              - StripPrefix=2
              
          # Project OpenApi Route Configuration
          - id: project_openapi_route
            uri: ${core-project-uri}
            predicates:
              - Path=/api/project/v3/**,/api/project/swagger-ui/**
            filters:

          # Project Api Route Configuration
          - id: project_route
            uri: ${core-project-uri}
            predicates:
              - Path=/api/project/**
            filters:
              - TokenRelay=
              - StripPrefix=2

          # Storage OpenApi Route Configuration
          - id: storage_openapi_route
            uri: ${core-storage-uri}
            predicates:
              - Path=/api/storage/v3/**, /api/storage/swagger-ui/**
            filters:

          # Storage Api Route Configuration
          - id: storage_route
            uri: ${core-storage-uri}
            predicates:
              - Path=/api/storage/**
            filters:
              - TokenRelay=
              - StripPrefix=2

          # Ai OpenApi Route Configuration
          - id: ai_openapi_route
            uri: ${core-ai-uri}
            predicates:
              - Path=/api/ai/v3/**, /api/ai/swagger-ui/**
            filters:

          # Ai Api Route Configuration
          - id: ai-route
            uri: ${core-ai-uri}
            predicates:
              - Path=/api/ai/**
            filters:
              - TokenRelay=
              - StripPrefix=2
              - RewritePath=/workflows, /workflows/

          # Messaging OpenApi Route Configuration
          - id: messaging_openapi_route
            uri: ${core-messaging-uri}
            predicates:
              - Path=/api/messaging/v3/**, /api/messaging/swagger-ui/**
            filters:

          # Messaging Api Route Configuration
          - id: messaging-route
            uri: ${core-messaging-uri}
            predicates:
              - Path=/api/messaging/**
            filters:
              - TokenRelay=
              - StripPrefix=2
          
          # LegalCase OpenApi Route Configuration
          - id: legalcase_openapi_route
            uri: ${legal-case-uri}
            predicates:
              - Path=/api/legalcase/v3/**, /api/legalcase/swagger-ui/**
            filters:

          # Storage Api Route Configuration
          - id: legalcase_route
            uri: ${legal-case-uri}
            predicates:
              - Path=/api/legalcase/**
            filters:
              - TokenRelay=
              - StripPrefix=2


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  
  security:
    oauth2:
      client:
        provider:
          core-identity:
            issuer-uri: ${AUTH_SERVER}
        registration:
          ginkgoo-bff-client:
            provider: core-identity
            client-id: ginkgoo-bff-client
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "${AUTH_CLIENT}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER}/oauth2/jwks
          issuer-uri: ${AUTH_SERVER}


management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false
      
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: core-gateway-service
        url: /v3/api-docs
      - name: core-identity-service
        url: /api/identity/v3/api-docs
      - name: core-workspace-service
        url: /api/workspace/v3/api-docs
      - name: core-project-service
        url: /api/project/v3/api-docs
      - name: core-storage-service
        url: /api/storage/v3/api-docs
      - name: core-ai-service
        url: /api/ai/v3/api-docs
      - name: core-messaging-service
        url: /api/messaging/v3/api-docs
      - name: legal-case-service
        url: /api/legalcase/v3/api-docs

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}
    org.springframework.web.cors: ${LOG_LEVEL_SPRING_WEB_CORS:DEBUG}
    com.ginkgooai: ${LOG_LEVEL_GINKGOOAI:DEBUG}
